ALTER TABLE myusers ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE myusers ALTER COLUMN created_at DROP DEFAULT;
ALTER TABLE myusers ALTER COLUMN updated_at DROP NOT NULL;
ALTER TABLE myusers ALTER COLUMN updated_at DROP DEFAULT;
DROP TRIGGER IF EXISTS set_updated_at ON myusers
